global:
  scrape_interval: 60s
  scrape_timeout: 20s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'itu-minitwit-app'
    static_configs:
      - targets: ['129.212.212.105:5000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
