# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "digital_ocean"
  config.ssh.private_key_path = "/Users/yumjihyeon/.ssh/id_rsa"
  config.ssh.username = "root"

  # [1] DigitalOcean setup
  config.vm.provider :digital_ocean do |provider|
    provider.token = ENV['DIGITAL_OCEAN_TOKEN']
    provider.ssh_key_name = "yumwlgus7@gmail.com"
    provider.ssh_key_path = "/Users/yumjihyeon/.ssh/id_rsa"
    provider.image = "ubuntu-22-04-x64"
    provider.region = "ams3"
    provider.size = "s-1vcpu-1gb"
  end

#  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  # [2] DB server
  config.vm.define "dbserver" do |db|
    db.vm.hostname = "dbserver"
    db.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y gnupg curl
      curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor
      echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
      sudo apt-get update
      sudo apt-get install -y mongodb-org
      sudo sed -i '/bindIp:/ s/127.0.0.1/0.0.0.0/' /etc/mongod.conf
      sudo systemctl start mongod
    SHELL
  end

  # [3] Web server
  config.vm.define "webserver" do |web|
    web.vm.hostname = "webserver"
    web.vm.synced_folder ".", "/vagrant", 
      type: "rsync",
      id: "vagrant-root",
      rsync__exclude: [".git/", "*.log", ".vagrant/"]

    web.vm.provider :digital_ocean do |do_os, override|
      override.vm.allowed_synced_folder_types = [:rsync]
    end

    web.vm.provision "shell", inline: <<-SHELL
      sudo pkill python3 || true
      Sudo apt-get update
      sudo apt-get install -y docker.io docker-compose
      sudo systemctl start docker
      sudo systemctl enable docker
      echo "Docker installation complete. Please run 'docker-compose up -d' in /vagrant"
    SHELL
  end
end
