{
 "title": "1st dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\".+\"}"
    }
   ]
  },
  { "title": "Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "minitwit_tweets_total[1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(minitwit_tweets_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webserver CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id!=\"/\"}[1m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Business KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "minitwit_users_total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(minitwit_users_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "flask_http_request_total", "legendFormat": "__auto" }
   ]
  }
 ]
}