name: Deploy Minitwit

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@e307f59d29c490a6140505a756627013e871e21b
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /vagrant
            git pull origin main
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up -d --build
            sudo docker image prune -f
